Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -58,6 +58,7 @@ jobs:
           android.api = 34
           android.ndk = 25b
           android.debug = 0
+          android.release_artifact = apk
           p4a.branch = develop
           android.accept_sdk_license = True
           log_level = 2
@@ -119,7 +120,7 @@ jobs:
           else
             echo "APK generation failed!"
             echo "Buildozer log:"
-            tail -n 200 buildozer.log
+            tail -n 200 .buildozer/android/platform/build-arm64-v8a/build/build.log || echo "Log not found"
             exit 1
           fi
 
